### ISSUE TITLE
Provide ability to slide

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/corona-viewer#5]
After fix for https://github.com/topcoder-platform/corona-viewer/issues/4 is in, provide a slider on the UI.

The slider will allow the user to "slide" through events.

@cwdcwd What should the start time of the slider be? Can the user change the start time?

**Comment by cwdcwd** [comment]
I think a slide to 7 days back would be enough. the Kafka bus is currently only configured to 14 days

**Comment by callmekatootie** [comment]
Fixed in 3435d7d7258e76d2c7025df3913f8667b7f9139b
